# Generated by Django 5.2.12 on 2026-03-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quizassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizassignment',
            name='time_limit_minutes',
        ),
        migrations.AddField(
            model_name='quizassignment',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
