# Generated by Django 5.2.12 on 2026-03-16 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_user_avatar_user_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_teacher',
            field=models.ForeignKey(blank=True, help_text='Master Admin: Assign this student to a specific teacher.', limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
