# Generated by Django 5.2.12 on 2026-03-16 11:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_assigned_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='assigned_teacher',
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_teachers',
            field=models.ManyToManyField(blank=True, help_text='Master Admin: Assign this student to multiple teachers.', limit_choices_to={'role': 'teacher'}, related_name='my_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
